name: avatar_plus
description: A versatile Flutter package for generating and displaying customizable avatars with random string content. Perfect for user profiles, placeholders, and more.
version: 0.0.5
homepage: https://github.com/YudizAndroidNareshP/Avatar-Plus
documentation: https://github.com/YudizAndroidNareshP/Avatar-Plus
issue_tracker: https://github.com/YudizAndroidNareshP/Avatar-Plus/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - avatar-generation
  - flutter-avatar
  - profile-picture
  - svg-avatars
  - random-avatar

screenshots:
  - description: A versatile Flutter package for generating and displaying customizable avatars with random string content.
    path: screenshots/logo.gif

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
